package promptrs:agent@0.2.0;

interface runner {
	run: func(input: string, config: string) -> string;
}

world agent {
	import promptrs:client/completion@0.2.0;
	import promptrs:parser/response@0.2.0;
	import promptrs:tools/caller@0.2.0;
	export runner;
}
