package promptrs:tools@0.2.0;

interface caller {
	record system {
		prompt: string,
		status-call: string,
	}

	record tool-delims {
		available-tools: tuple<string, string>,
		tool-call: tuple<string, string>,
	}

	record tool-response {
		output: string,
		score: f64,
	}

	init: func(delims: tool-delims) -> system;
	status: func() -> tool-response;
	call: func(name: string, arguments: string) -> tool-response;
}

world tools {
	export caller;
}
