name: Publish

on:
  push:
    tags: [v*]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Rust toolchain for wasm32-wasip2
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-wasip2
      - name: Build
        run: cargo build --release --target wasm32-wasip2
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Get version
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/promptrs/unit-agent
          tags: |
            type=semver,pattern={{version}}
      - name: Publish to Container Registry
        uses: bytecodealliance/wkg-github-action@v5
        with:
            oci-reference-without-tag: '${{ env.REGISTRY }}/promptrs/unit-agent'
            file: 'target/wasm32-wasip2/release/unit_agent.wasm'
            description: 'Entrypoint for unit-agents in promptrs workflows'
            source: 'https://github.com/promptrs/agent'
            homepage: 'https://github.com/promptrs/agent'
            version: ${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.version'] }}
            licenses: 'MIT'
